CREATE TABLE users (
  id              BIGINT PRIMARY KEY AUTO_INCREMENT,
  role_id         TINYINT NOT NULL,
  first_name      VARCHAR(50) NOT NULL,
  last_name       VARCHAR(50) NOT NULL,
  email           VARCHAR(100) NOT NULL UNIQUE,
  password_hash   VARCHAR(255) NOT NULL,
  phone           VARCHAR(15),
  avatar_url      VARCHAR(500),
  is_verified     BOOLEAN DEFAULT FALSE,
  is_active       BOOLEAN DEFAULT TRUE,
  is_banned       BOOLEAN DEFAULT FALSE,
  email_token     VARCHAR(255),
  reset_token     VARCHAR(255),
  reset_expires   TIMESTAMP NULL,
  is_deleted      BOOLEAN DEFAULT FALSE,
  deleted_at      TIMESTAMP NULL,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by      BIGINT NULL,
  updated_by      BIGINT NULL,
  FOREIGN KEY (role_id) REFERENCES roles(id),
  INDEX idx_users_email (email),
  INDEX idx_users_role (role_id)
);
