CREATE TABLE sellers (
  id              BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id         BIGINT NOT NULL UNIQUE,
  business_name   VARCHAR(100) NOT NULL,
  business_email  VARCHAR(100),
  gst_number      VARCHAR(20),
  pan_number      VARCHAR(20),
  bank_account    VARCHAR(30),
  ifsc_code       VARCHAR(15),
  status          ENUM('PENDING','APPROVED','SUSPENDED','REJECTED') DEFAULT 'PENDING',
  rejection_note  TEXT,
  approval_date   TIMESTAMP NULL,
  approved_by     BIGINT NULL,
  logo_url        VARCHAR(500),
  description     TEXT,
  total_revenue   DECIMAL(15,2) DEFAULT 0.00,
  is_deleted      BOOLEAN DEFAULT FALSE,
  deleted_at      TIMESTAMP NULL,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by      BIGINT NULL,
  updated_by      BIGINT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id),
  INDEX idx_sellers_status (status)
);
