CREATE TABLE products (
  id                BIGINT PRIMARY KEY AUTO_INCREMENT,
  seller_id         BIGINT NOT NULL,
  category_id       INT NOT NULL,
  sub_category_id   INT,
  brand_id          INT,
  name              VARCHAR(255) NOT NULL,
  slug              VARCHAR(300) NOT NULL UNIQUE,
  description       TEXT,
  short_description VARCHAR(500),
  sku               VARCHAR(100) UNIQUE,
  base_price        DECIMAL(10,2) NOT NULL,
  selling_price     DECIMAL(10,2) NOT NULL,
  discount_percent  DECIMAL(5,2) DEFAULT 0.00,
  has_variants      BOOLEAN DEFAULT FALSE,
  tags              VARCHAR(1000),
  is_active         BOOLEAN DEFAULT TRUE,
  is_featured       BOOLEAN DEFAULT FALSE,
  avg_rating        DECIMAL(3,2) DEFAULT 0.00,
  review_count      INT DEFAULT 0,
  view_count        INT DEFAULT 0,
  is_deleted        BOOLEAN DEFAULT FALSE,
  deleted_at        TIMESTAMP NULL,
  created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by        BIGINT NULL,
  updated_by        BIGINT NULL,
  FOREIGN KEY (seller_id) REFERENCES sellers(id),
  FOREIGN KEY (category_id) REFERENCES categories(id),
  FOREIGN KEY (sub_category_id) REFERENCES sub_categories(id),
  FOREIGN KEY (brand_id) REFERENCES brands(id),
  INDEX idx_products_seller (seller_id),
  INDEX idx_products_category (category_id),
  INDEX idx_products_sub_category (sub_category_id),
  INDEX idx_products_brand (brand_id),
  INDEX idx_products_slug (slug),
  INDEX idx_products_active_featured (is_active, is_featured),
  INDEX idx_products_price (selling_price),
  INDEX idx_products_rating (avg_rating),
  FULLTEXT INDEX idx_products_search (name, description, tags)
);
