CREATE TABLE coupons (
  id               BIGINT PRIMARY KEY AUTO_INCREMENT,
  seller_id        BIGINT NULL,
  category_id      INT NULL,
  code             VARCHAR(30) NOT NULL UNIQUE,
  description      VARCHAR(200),
  discount_type    ENUM('PERCENT','FLAT') NOT NULL,
  discount_value   DECIMAL(10,2) NOT NULL,
  min_order_value  DECIMAL(10,2) DEFAULT 0.00,
  max_discount     DECIMAL(10,2) NULL,
  usage_limit      INT NULL,
  usage_per_user   INT DEFAULT 1,
  used_count       INT DEFAULT 0,
  is_active        BOOLEAN DEFAULT TRUE,
  expires_at       TIMESTAMP NULL,
  is_deleted       BOOLEAN DEFAULT FALSE,
  deleted_at       TIMESTAMP NULL,
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by       BIGINT NULL,
  updated_by       BIGINT NULL,
  FOREIGN KEY (seller_id) REFERENCES sellers(id),
  FOREIGN KEY (category_id) REFERENCES categories(id),
  INDEX idx_coupons_code (code),
  INDEX idx_coupons_active_expiry (is_active, expires_at)
);
