CREATE TABLE orders (
  id                BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id           BIGINT NOT NULL,
  address_id        BIGINT NOT NULL,
  coupon_id         BIGINT NULL,
  order_number      VARCHAR(30) NOT NULL UNIQUE,
  status            ENUM('PENDING','CONFIRMED','PACKED','SHIPPED','OUT_FOR_DELIVERY','DELIVERED','CANCELLED','REFUNDED') DEFAULT 'PENDING',
  sub_total         DECIMAL(12,2) NOT NULL,
  discount_amount   DECIMAL(12,2) DEFAULT 0.00,
  shipping_fee      DECIMAL(8,2) DEFAULT 0.00,
  total_amount      DECIMAL(12,2) NOT NULL,
  currency          VARCHAR(3) DEFAULT 'INR',
  notes             TEXT,
  invoice_url       VARCHAR(500) NULL,
  is_deleted        BOOLEAN DEFAULT FALSE,
  deleted_at        TIMESTAMP NULL,
  created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by        BIGINT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (address_id) REFERENCES addresses(id),
  FOREIGN KEY (coupon_id) REFERENCES coupons(id),
  INDEX idx_orders_user (user_id),
  INDEX idx_orders_status (status),
  INDEX idx_orders_number (order_number),
  INDEX idx_orders_created (created_at)
);
