CREATE TABLE order_items (
  id              BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id        BIGINT NOT NULL,
  product_id      BIGINT NOT NULL,
  variant_id      BIGINT NULL,
  seller_id       BIGINT NOT NULL,
  product_name    VARCHAR(255) NOT NULL,
  product_image   VARCHAR(500),
  variant_label   VARCHAR(200),
  unit_price      DECIMAL(10,2) NOT NULL,
  quantity        INT NOT NULL,
  total_price     DECIMAL(10,2) NOT NULL,
  item_status     ENUM('PENDING','CONFIRMED','PACKED','SHIPPED','OUT_FOR_DELIVERY','DELIVERED','CANCELLED') DEFAULT 'PENDING',
  tracking_number VARCHAR(100),
  carrier         VARCHAR(100),
  shipped_at      TIMESTAMP NULL,
  delivered_at    TIMESTAMP NULL,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products(id),
  FOREIGN KEY (variant_id) REFERENCES product_variants(id),
  FOREIGN KEY (seller_id) REFERENCES sellers(id),
  INDEX idx_order_items_order (order_id),
  INDEX idx_order_items_seller (seller_id),
  INDEX idx_order_items_product (product_id)
);
