// ARC CART – Rich Mock Data
// Used until backend API is connected

export const mockCategories = [
  { id: 1, name: 'Electronics', icon: '💻', imageUrl: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=300', count: 1240, color: '#1e90ff' },
  { id: 2, name: 'Fashion', icon: '👗', imageUrl: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=300', count: 856, color: '#a855f7' },
  { id: 3, name: 'Home & Kitchen', icon: '🏠', imageUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=300', count: 642, color: '#10b981' },
  { id: 4, name: 'Sports', icon: '⚽', imageUrl: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=300', count: 438, color: '#f59e0b' },
  { id: 5, name: 'Books', icon: '📚', imageUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=300', count: 320, color: '#ef4444' },
  { id: 6, name: 'Gaming', icon: '🎮', imageUrl: 'https://images.unsplash.com/photo-1593118247619-e2d6f056869e?w=300', count: 275, color: '#8b5cf6' },
  { id: 7, name: 'Beauty', icon: '💄', imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=300', count: 389, color: '#ec4899' },
  { id: 8, name: 'Automotive', icon: '🚗', imageUrl: 'https://images.unsplash.com/photo-1485291571150-772bcfc10da5?w=300', count: 196, color: '#06b6d4' },
];

export const mockBrands = [
  { id: 1, name: 'Apple', logo: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg' },
  { id: 2, name: 'Samsung', logo: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Samsung_Logo.svg' },
  { id: 3, name: 'Sony', logo: 'https://upload.wikimedia.org/wikipedia/commons/c/ca/Sony_logo.svg' },
  { id: 4, name: 'Nike', logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Logo_NIKE.svg' },
  { id: 5, name: 'Adidas', logo: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Adidas_Logo.svg' },
  { id: 6, name: 'OnePlus', logo: '' },
  { id: 7, name: 'Lenovo', logo: '' },
  { id: 8, name: 'Bose', logo: '' },
];

export const mockProducts = [
  {
    id: 1,
    name: 'Sony WH-1000XM5 Wireless Headphones',
    category: 'Electronics',
    categoryId: 1,
    brand: 'Sony',
    sellingPrice: 24990,
    basePrice: 34990,
    discount: 29,
    rating: 4.8,
    reviewCount: 2847,
    images: [
      { id: 1, imageUrl: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600', isMain: true },
      { id: 2, imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600' },
      { id: 3, imageUrl: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600' },
    ],
    inStock: true,
    isNew: false,
    isTrending: true,
    isFeatured: true,
    isFlashSale: false,
    description: 'Industry-leading noise cancellation with the next-level quiet and exceptional sound quality. Redesigned for more comfortable fit, the WH-1000XM5 leads with innovative technology.',
    specifications: {
      'Driver Size': '30mm',
      'Frequency Response': '4Hz-40,000Hz',
      'Battery Life': '30 hours',
      'Noise Cancellation': 'Yes - Dual processor',
      'Connectivity': 'Bluetooth 5.2',
      'Weight': '250g',
    },
    tags: ['wireless', 'noise-cancelling', 'premium', 'headphones'],
  },
  {
    id: 2,
    name: 'Apple MacBook Air M3 13"',
    category: 'Electronics',
    categoryId: 1,
    brand: 'Apple',
    sellingPrice: 114900,
    basePrice: 119900,
    discount: 4,
    rating: 4.9,
    reviewCount: 1243,
    images: [
      { id: 1, imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600', isMain: true },
      { id: 2, imageUrl: 'https://images.unsplash.com/photo-1611186871525-9d571f85e5ca?w=600' },
    ],
    inStock: true,
    isNew: true,
    isTrending: true,
    isFeatured: true,
    isFlashSale: false,
    description: 'MacBook Air with M3 chip. Up to 18 hours of battery life, up to 24GB unified memory, and a beautiful Liquid Retina display.',
    specifications: {
      'Chip': 'Apple M3',
      'RAM': '8GB Unified Memory',
      'Storage': '256GB SSD',
      'Display': '13.6-inch Liquid Retina',
      'Battery': 'Up to 18 hours',
      'Weight': '1.24 kg',
    },
    tags: ['laptop', 'apple', 'M3', 'ultrabook'],
  },
  {
    id: 3,
    name: 'Samsung Galaxy S24 Ultra 5G',
    category: 'Electronics',
    categoryId: 1,
    brand: 'Samsung',
    sellingPrice: 89999,
    basePrice: 134999,
    discount: 33,
    rating: 4.7,
    reviewCount: 3128,
    images: [
      { id: 1, imageUrl: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600', isMain: true },
      { id: 2, imageUrl: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=600' },
    ],
    inStock: true,
    isNew: false,
    isTrending: true,
    isFeatured: true,
    isFlashSale: true,
    description: '200MP pro-grade camera system with S Pen included. The most advanced Galaxy phone ever with Galaxy AI.',
    specifications: {
      'Processor': 'Snapdragon 8 Gen 3',
      'RAM': '12GB',
      'Storage': '256GB',
      'Camera': '200MP + 12MP + 10MP + 50MP',
      'Battery': '5000mAh',
      'Display': '6.8" Dynamic AMOLED 2X',
    },
    tags: ['smartphone', 'samsung', 'flagship', '5G'],
  },
  {
    id: 4,
    name: 'Nike Air Jordan 1 Retro High OG',
    category: 'Fashion',
    categoryId: 2,
    brand: 'Nike',
    sellingPrice: 11995,
    basePrice: 14995,
    discount: 20,
    rating: 4.6,
    reviewCount: 892,
    images: [
      { id: 1, imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600', isMain: true },
      { id: 2, imageUrl: 'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=600' },
    ],
    inStock: true,
    isNew: false,
    isTrending: true,
    isFeatured: false,
    isFlashSale: true,
    description: 'The iconic Air Jordan 1 Retro High OG in classic colorway. Premium leather upper with Nike Air cushioning.',
    specifications: {
      'Upper': 'Premium Leather',
      'Outsole': 'Non-marking rubber',
      'Closure': 'Lace-up',
      'Style': 'Basketball / Lifestyle',
      'Available Sizes': '6-13 US',
    },
    tags: ['sneakers', 'jordan', 'nike', 'shoes'],
  },
  {
    id: 5,
    name: 'LG OLED 55" 4K Smart TV',
    category: 'Electronics',
    categoryId: 1,
    brand: 'LG',
    sellingPrice: 79990,
    basePrice: 119990,
    discount: 33,
    rating: 4.8,
    reviewCount: 654,
    images: [
      { id: 1, imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f4834c?w=600', isMain: true },
    ],
    inStock: true,
    isNew: false,
    isTrending: false,
    isFeatured: true,
    isFlashSale: false,
    description: 'Self-lit OLED pixels for perfect black, stunning contrast, and vivid colors. α9 Gen6 AI Processor 4K for ultimate clarity.',
    specifications: {
      'Display': '55" OLED 4K',
      'Resolution': '3840 x 2160',
      'HDR': 'Dolby Vision IQ',
      'Smart Platform': 'webOS 23',
      'Refresh Rate': '120Hz',
    },
    tags: ['TV', 'OLED', '4K', 'smart'],
  },
  {
    id: 6,
    name: 'Dyson V15 Detect Vacuum Cleaner',
    category: 'Home & Kitchen',
    categoryId: 3,
    brand: 'Dyson',
    sellingPrice: 49900,
    basePrice: 64900,
    discount: 23,
    rating: 4.7,
    reviewCount: 441,
    images: [
      { id: 1, imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600', isMain: true },
    ],
    inStock: true,
    isNew: false,
    isTrending: false,
    isFeatured: true,
    isFlashSale: false,
    description: 'Laser dust detection, LCD screen, and most powerful Dyson motor ever. Reveals and counts invisible dust particles.',
    specifications: {
      'Suction': '240 AW',
      'Runtime': '60 minutes',
      'Bin Volume': '0.77L',
      'Motor': 'Dyson Hyperdymium',
      'Filtration': 'Whole-machine HEPA',
    },
    tags: ['vacuum', 'dyson', 'cordless', 'home'],
  },
  {
    id: 7,
    name: 'Canon EOS R50 Mirrorless Camera',
    category: 'Electronics',
    categoryId: 1,
    brand: 'Canon',
    sellingPrice: 54990,
    basePrice: 69990,
    discount: 21,
    rating: 4.6,
    reviewCount: 328,
    images: [
      { id: 1, imageUrl: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600', isMain: true },
      { id: 2, imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600' },
    ],
    inStock: true,
    isNew: true,
    isTrending: false,
    isFeatured: true,
    isFlashSale: false,
    description: '24.2 Megapixel APS-C sensor with Dual Pixel CMOS AF II. Perfect for content creators and photography enthusiasts.',
    specifications: {
      'Sensor': '24.2 MP APS-C CMOS',
      'AF Points': '651-point Dual Pixel',
      'Video': '4K 30fps',
      'Display': '3" Vari-angle Touch LCD',
      'Weight': '375g',
    },
    tags: ['camera', 'mirrorless', 'canon', 'photography'],
  },
  {
    id: 8,
    name: 'boAt Airdopes 141 TWS Earbuds',
    category: 'Electronics',
    categoryId: 1,
    brand: 'boAt',
    sellingPrice: 1299,
    basePrice: 4990,
    discount: 74,
    rating: 4.2,
    reviewCount: 18742,
    images: [
      { id: 1, imageUrl: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600', isMain: true },
    ],
    inStock: true,
    isNew: false,
    isTrending: true,
    isFeatured: false,
    isFlashSale: true,
    description: '10mm drivers with boAt Signature Sound, 42 hours total playback, and IPX4 water resistance. BEAST Mode for gaming.',
    specifications: {
      'Driver': '10mm',
      'Battery': '42 hours total',
      'Water Resistance': 'IPX4',
      'Connectivity': 'Bluetooth 5.3',
      'Mic': 'Quad Mic with ENx',
    },
    tags: ['earbuds', 'TWS', 'wireless', 'budget'],
  },
  {
    id: 9,
    name: 'Adidas Ultraboost 23 Running Shoes',
    category: 'Sports',
    categoryId: 4,
    brand: 'Adidas',
    sellingPrice: 8999,
    basePrice: 14999,
    discount: 40,
    rating: 4.5,
    reviewCount: 1124,
    images: [
      { id: 1, imageUrl: 'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=600', isMain: true },
    ],
    inStock: true,
    isNew: false,
    isTrending: true,
    isFeatured: false,
    isFlashSale: false,
    description: 'BOOST midsole energy return with Primeknit upper for ultimate running comfort and performance.',
    specifications: {
      'Upper': 'Primeknit+',
      'Midsole': 'BOOST',
      'Outsole': 'Continental Rubber',
      'Drop': '10mm',
    },
    tags: ['running', 'shoes', 'adidas', 'sports'],
  },
  {
    id: 10,
    name: 'OnePlus 12 5G Smartphone',
    category: 'Electronics',
    categoryId: 1,
    brand: 'OnePlus',
    sellingPrice: 64999,
    basePrice: 69999,
    discount: 7,
    rating: 4.6,
    reviewCount: 2341,
    images: [
      { id: 1, imageUrl: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600', isMain: true },
    ],
    inStock: true,
    isNew: true,
    isTrending: false,
    isFeatured: false,
    isFlashSale: false,
    description: 'Snapdragon 8 Gen 3, Hasselblad Camera, 100W SUPERVOOC charging, and 5400mAh battery.',
    specifications: {
      'Processor': 'Snapdragon 8 Gen 3',
      'RAM': '12GB LPDDR5X',
      'Storage': '256GB UFS 3.1',
      'Camera': '50MP + 48MP + 64MP Hasselblad',
      'Battery': '5400mAh + 100W',
      'Display': '6.82" 1440p LTPO AMOLED 120Hz',
    },
    tags: ['smartphone', 'oneplus', 'flagship', '5G'],
  },
  {
    id: 11,
    name: 'Instant Pot Duo 7-in-1 Pressure Cooker',
    category: 'Home & Kitchen',
    categoryId: 3,
    brand: 'Instant Pot',
    sellingPrice: 6499,
    basePrice: 9999,
    discount: 35,
    rating: 4.7,
    reviewCount: 5621,
    images: [
      { id: 1, imageUrl: 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=600', isMain: true },
    ],
    inStock: true,
    isNew: false,
    isTrending: false,
    isFeatured: false,
    isFlashSale: false,
    description: '7-in-1 multi-use programmable cooker: pressure cooker, slow cooker, rice cooker, steamer, sauté, yogurt maker, and warmer.',
    specifications: {
      'Capacity': '6 Quart',
      'Programs': '14 Smart Programs',
      'Voltage': '220-240V',
      'Material': 'Stainless Steel',
    },
    tags: ['kitchen', 'pressure-cooker', 'instant-pot', 'cooking'],
  },
  {
    id: 12,
    name: 'Lenovo Legion 5i Pro Gaming Laptop',
    category: 'Electronics',
    categoryId: 1,
    brand: 'Lenovo',
    sellingPrice: 94990,
    basePrice: 129990,
    discount: 27,
    rating: 4.7,
    reviewCount: 876,
    images: [
      { id: 1, imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600', isMain: true },
    ],
    inStock: true,
    isNew: false,
    isTrending: true,
    isFeatured: true,
    isFlashSale: false,
    description: 'Intel Core i7-13700HX, NVIDIA RTX 4060 8GB, 16" 2560x1600 IPS 165Hz display. Dominate every game.',
    specifications: {
      'Processor': 'Intel Core i7-13700HX',
      'GPU': 'NVIDIA RTX 4060 8GB',
      'RAM': '16GB DDR5',
      'Storage': '512GB NVMe SSD',
      'Display': '16" 2K IPS 165Hz',
      'Battery': '80Whr',
    },
    tags: ['gaming', 'laptop', 'lenovo', 'RTX'],
  },
];

export const mockReviews = [
  {
    id: 1,
    name: 'Arjun Sharma',
    avatar: 'https://i.pravatar.cc/60?img=11',
    rating: 5,
    comment: 'Absolutely love this platform! Fast delivery, genuine products, and the UI is incredibly smooth. ARC CART is my go-to for all electronics.',
    product: 'Sony WH-1000XM5',
    location: 'Mumbai, India',
    date: '2 days ago',
    verified: true,
  },
  {
    id: 2,
    name: 'Priya Nair',
    avatar: 'https://i.pravatar.cc/60?img=5',
    rating: 5,
    comment: 'The product quality is amazing and the packaging was perfect. Got my MacBook Air in 2 days. The checkout process was super seamless!',
    product: 'Apple MacBook Air M3',
    location: 'Bangalore, India',
    date: '1 week ago',
    verified: true,
  },
  {
    id: 3,
    name: 'Rahul Verma',
    avatar: 'https://i.pravatar.cc/60?img=8',
    rating: 5,
    comment: 'Best e-commerce experience I have had! Premium UI, great deals, and lightning-fast delivery. This is truly the future of smart shopping.',
    product: 'Samsung Galaxy S24 Ultra',
    location: 'Delhi, India',
    date: '3 days ago',
    verified: true,
  },
  {
    id: 4,
    name: 'Sneha Patel',
    avatar: 'https://i.pravatar.cc/60?img=16',
    rating: 4,
    comment: 'Really impressed with the product variety and pricing. The app feels premium and the recommendations are spot on. Will definitely keep shopping here.',
    product: 'Nike Air Jordan 1',
    location: 'Ahmedabad, India',
    date: '5 days ago',
    verified: true,
  },
];

export const mockOrders = [
  {
    id: 'ARC-2024-001',
    date: '2024-01-15',
    status: 'DELIVERED',
    total: 24990,
    items: [{ ...mockProducts[0], quantity: 1 }],
    deliveryDate: '2024-01-17',
    address: '123, MG Road, Bangalore - 560001',
  },
  {
    id: 'ARC-2024-002',
    date: '2024-01-20',
    status: 'SHIPPED',
    total: 11995,
    items: [{ ...mockProducts[3], quantity: 1 }],
    estimatedDelivery: '2024-01-23',
    address: '456, Koramangala, Bangalore - 560034',
  },
  {
    id: 'ARC-2024-003',
    date: '2024-01-22',
    status: 'PROCESSING',
    total: 89999,
    items: [{ ...mockProducts[2], quantity: 1 }],
    estimatedDelivery: '2024-01-26',
    address: '789, Indiranagar, Bangalore - 560038',
  },
];

export const flashSaleProducts = mockProducts.filter(p => p.isFlashSale);
export const featuredProducts = mockProducts.filter(p => p.isFeatured);
export const trendingProducts = mockProducts.filter(p => p.isTrending);
export const newArrivals = mockProducts.filter(p => p.isNew);

export const FLASH_SALE_END = new Date(Date.now() + 6 * 60 * 60 * 1000); // 6 hours from now
